### PR TITLE
contr functions from kknn

### PR DESCRIPTION
**Pull request by Kucharssim**
fixes https://github.com/jasp-stats/jasp-test-release/issues/2000

for some reason simply adding the function names to the `doNotRemoveAnyOfThese` here:
https://github.com/jasp-stats/jaspBase/blob/5e839aa73965233894953b16d509cc778c435f88/R/memoryMaintenance.R#L24

did not work, but importing these functions into `jaspBase` did... this means this PR is adding `kknn` as a dependency to `jaspBase`, which less than great. 

But maybe @JorisGoosen had a different idea for the fix and I misunderstood...

### CODE REVIEW

**Comment by JorisGoosen** [comment]
Ok my idea of a fix doesnt seem to work but depending on `kknn` is also bad....

@vandenman ?

**Comment by vandenman** [comment]
I haven't looked into this but since we're already using a fork of kknn (vandenman/kknn), can't we fix this there?

**Comment by Kucharssim** [comment]
We could in theory just copy paste the functions from `kknn`, so that `jaspBase` does not have to depend on it. The downside is that it's just stupid ugly solution (and we need check how to include it such that we don't break `kknn`'s license)

**Comment by JorisGoosen** [comment]
> I haven't looked into this but since we're already using a fork of kknn (vandenman/kknn), can't we fix this there?

This sounds like my favourite solution

Also, could we not make dummy functions in `jaspBase` that simply call `kknn` if available and not otherwise.
Then we could put `kknn` in suggests?

**Comment by Kucharssim** [comment]
> I haven't looked into this but since we're already using a fork of kknn (vandenman/kknn), can't we fix this there?

Well it's possible, but since `kknn` uses these functions by setting them as values of `contrasts` in `options()`, it's kind of pain to make sure that you don't miss anything as the functions can be in theory called implicitly from anywhere.

**Comment by Kucharssim** [comment]
lol, well the easiest option is to fix it directly in `jaspMachineLearning`, no need for fiddling with `jaspBase` or `kknn` apparently...

**Review by JorisGoosen — APPROVED** [review]

**Comment by Kucharssim** [comment]
Yeah the other fixes did not really work

**Pull request merged**
