### PR TITLE
Tweak configure script and remove the terrible hacks

### PR DESCRIPTION
**Pull request by vandenman**
Maybe we also need to tweak `install-jaspBase.R.in` in jasp-desktop.

### CODE REVIEW

**Comment by JorisGoosen** [comment]
Should I review and merge this if ok @vandenman ?

**Comment by vandenman** [comment]
Yes, I'm also making a sister pr to jasp-desktop after lunch that fixes the installation of jaspBase

**Review by JorisGoosen — APPROVED** [review]

**Comment by JorisGoosen** [comment]
Ok, this all looks good, Ill wait for that other PR so I can test it properly

**Comment by vandenman** [comment]
the last commit avoids this error for me: https://github.com/jasp-stats/INTERNAL-jasp/issues/2067#issue-1329805758

**Review by JorisGoosen — APPROVED** [review]

**Pull request merged**
