### PR TITLE
Fixed a typo! 🖊

### PR DESCRIPTION
**Pull request by amirmasoudabdol**
Unless we went for French there! 😬

### CODE REVIEW

**Comment by JorisGoosen** [comment]
Or dutch for that matter ;)

**Comment by JorisGoosen** [comment]
But doesnt this break 
```
	std::string		result			= jaspRCPP_evalRCode(moduleCode.c_str(), false);
	bool			succes			= result == "succes!"; //Defined in DynamicModule::succesResultString()
```
at https://github.com/jasp-stats/jasp-desktop/blob/ef60937d81e5388ed2f27f6047cc1363e9af4611/Engine/engine.cpp#L442 ?
Im not sure about it but it is quite likely.

Im not happy about strings to communicate succes etc, but R is not easily coupled with `class enum` etc.

**Comment by amirmasoudabdol** [comment]
That looks like that it will break! If the success and failure are the only two messages, this might makes sense to just use 0, and 1, and they can be casted to bool easily anyway?

**Comment by JorisGoosen** [comment]
> That looks like that it will break! If the success and failure are the only two messages, this might makes sense to just use 0, and 1, and they can be casted to `bool` easily anyway?

possibly but it is a lot easier to do so later because if this is merged we break `development`.
And I don't mind a bit of dutch/french in the codebase. Much better than this tongue.

**Comment by amirmasoudabdol** [comment]
Sure, it's not a big deal anyway. I just noticed it and made a quick PR on GitHub!

**Pull request closed without merging**
