### PR TITLE
add default values for .numDecimals etc when not running in JASP

### PR DESCRIPTION
**Pull request by JorisGoosen**
For https://github.com/jasp-stats/INTERNAL-jasp/issues/2172

### CODE REVIEW

**Comment by vandenman** [comment]
I mean this might work but it isn't a really nice solution.

What we need to have on the R side have some object (or function), say `jaspOptions`, that analyses can ask for global preferences. Then we don't have to pollute the global environment so much.

Whenever analyses then call `jaspOptions("numDecimals")` we retrieve the value for that preference (which can be cached of course).

shall I try to add that after this is merged?

**Comment by JorisGoosen** [comment]
> I mean this might work but it isn't a really nice solution.
> 
> What we need to have on the R side have some object (or function), say `jaspOptions`, that analyses can ask for global preferences. Then we don't have to pollute the global environment so much.
> 
> Whenever analyses then call `jaspOptions("numDecimals")` we retrieve the value for that preference (which can be cached of course).
> 
> shall I try to add that after this is merged?

You are right this isn't pretty but it is also what we've been doing for a while now. The polluting that is.

The jaspOptions or whatever seems like a great solution but I think it'd be better if we made an issue for that and postpone it until at least the next version. And this can be done together with the splitting of of QMLComponents etc.

There we need to make all sorts of settings available in any case.

**Comment by vandenman** [comment]
ok, I created an issue so we can let the topic rest for now.

**Comment by vandenman** [comment]
I'm not 100% sure if this will work correctly, although I think it will (you're basically assuming that the lookup mechanism of R finds these values). Either way, this won't break existing analyses that don't use it so it's pretty harmless. If you'd want to be more safe you could put it in a `if (jaspResultsCalledFromJasp()) { ... }` instead.

**Comment by JorisGoosen** [comment]
> you're basically assuming that the lookup mechanism of R finds these values

Indeed I am, as the function call is right below it and scoping in R simply looks in the environment up when it can't find something right?

I agree it is ugly but the new issue you made will entail cleaning this up anyway.

**Review by vandenman — APPROVED** [review]

**Pull request merged**
